version: "2"

services:
  sonarqube:
    image: sjatgutzmann/docker.centos.sonarqube
    ports:
      - "9000:9000"
#    networks:
#      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      # -/opt/sonarqube-6.1/web
      - sonarqube_conf:/opt/sonarqube-6.1/conf
      - sonarqube_data:/opt/sonarqube-6.1/data
      - sonarqube_extensions:/opt/sonarqube-6.1/extensions
      - sonarqube_bundled_plugins:/opt/sonarqube-6.1/lib/bundled-plugins
    depends_on:
      - db

  db:
    image: sjatgutzmann/docker.centos.postgres
#    networks:
#      - sonarnet
    environment:
      - PG_CREATE_USER=sonar,archiva
      - PG_CREATE_PASSWORD=sonar,archiva
      - PG_CREATE_DB=sonar,archiva_users
    volumes:
      #- postgresql:/var/lib/postgresql
      - postgres4all:/var/log/postgres
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      # - postgresql_data:/var/lib/postgresql/data
      - pgdata4all:/var/lib/pgsql/9.3/data

  git:
    image: sjatgutzmann/docker.centos.gitblit
    environment:
      - HTTP_PORT=9080
      - HTTPS_PORT=9443
      # mirror another gitblit server
      - FEDERATION1_URL=https://dev.gitblit.com
      # token from the log of the gitblit server to mirror
      - FEDERATION1_TOKEN=6f3b8a24bf970f17289b234284c94f43eb42f0e4
      - FEDERATION1_MIRROR=true
      - FEDERATION1_BARE=true
      - FEDERATION1_MERGE_ACCOUNTS=false
      - FEDERATION1_TIME=60 mins
      - FEDERATION1_FOLDER=gitblit 
    ports:
      - 9080:9080
      - 9443:9443
      - 9418:9418
      - 29418:29418
    volumes:
      - gitblit_data:/opt/gitblit/data

  jenkins:
    image: sjatgutzmann/docker.centos.jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

  archiva:
    image: sjatgutzmann/docker.centos.archiva
    environment:
      - HTTP_PORT=8585
      - DO_INIT=true
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_USER=archiva
      - DB_PASS=archiva
      - USERS_DB_NAME=archiva_users
    ports:
      - 8282:8585
    volumes:
      - archiva_data:/archiva-data
    depends_on:
      - db
  
  pgadmin:
    image: sjatgutzmann/docker.centos.pgadmin
    ports:
      - 9898:8080
    depends_on:
      - db    
    
#networks:
#  sonarnet:
#    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled_plugins:
  postgres4all:
  pgdata4all:
  gitblit_data:
  jenkins_home:
  archiva_data:  
